version: '3.8'

services:
  # Servicio de la aplicación Flask expuesta en GHCR
  flask_app:
    image: ghcr.io/<davmorenoga>/tallerenclase01-07-2025:latest
    container_name: flask_prometheus_app
    ports:
      - "8000:8000"
    networks:
      - monitor-net
    restart: unless-stopped

  # Servicio Prometheus para recolectar métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  # Servicio Grafana para visualizar métricas
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net
    depends_on:
      - prometheus

# Definición de volúmenes y redes
volumes:
  grafana-storage:

networks:
  monitor-net:
