name: Deploy App to EC2

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy app on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/TallerEnClase01-07-2025
          git pull origin main
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GT_TOKEN }}
          docker compose pull flask_app
          docker compose up -d flask_app
