name: Deploy Monitoring Stack

on:
  workflow_dispatch:
  push:
    paths:
      - 'monitoring/**'
      - 'grafana/**'
      - 'docker-compose.yml'
  workflow_run:
    workflows: ["Deploy App to EC2"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy monitoring services on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/TallerEnClase01-07-2025
          git pull origin main
          docker compose up -d prometheus grafana
